steps:
  - id: Build the container image
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', '${_IMAGE}', '-t', '${_IMAGE_LATEST}', '.' ]

  - id: Run the container image
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'run', '-d', '-p', '9050:9050', '${_IMAGE}' ]

  - id: Test the container image
    name: 'gcr.io/cloud-builders/curl'
    args: [ '--fail', '--socks5',  '127.0.0.1:9050', '--socks5-hostname', '127.0.0.1:9050', 'https://check.torproject.org/api/ip', '||', 'exit 1' ]

#  - id: Push the container image to Artifact Registry
#    name: 'gcr.io/cloud-builders/docker'
#    args: [ 'push', '${_IMAGE}' ]

substitutions:
  _IMAGE: 'europe-west4-docker.pkg.dev/${PROJECT_ID}/docker/tor-client:${SHORT_SHA}'
  _IMAGE_LATEST: 'europe-west4-docker.pkg.dev/${PROJECT_ID}/docker/tor-client:latest'
options:
  dynamic_substitutions: true

#images:
#  - '${_IMAGE}'
#  - '${_IMAGE_LATEST}'
