name: Deploy to VPS

on:
  workflow_call:
    inputs:
      version:
        description: version tag
        required: true
        type: string
  workflow_dispatch:
    inputs:
      version:
        description: version tag
        required: true
        default: latest
        type: string

env:
  CONTAINER_NAME: tor-client

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to VPS
    steps:
      - uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script_stop: true
          script: |
            echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
            docker container stop ${{ env.CONTAINER_NAME }} || true && docker container rm ${{ env.CONTAINER_NAME }} || true
            docker run -d -p 32905:32905 --restart always --name ${{ env.CONTAINER_NAME }} ${{ vars.IMAGE_NAME }}:${{ inputs.version }}
            docker ps