name: Deploy to VPS

on:
  workflow_call:
    inputs:
      version:
        description: version tag
        required: true
        type: string
  workflow_dispatch:
    inputs:
      version:
        description: version tag
        required: true
        default: latest
        type: string

env:
  CONTAINER_NAME: tor-client

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to VPS
    steps:
      - uses: appleboy/ssh-action@v1.2.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            set -e
            echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
            docker container stop ${{ env.CONTAINER_NAME }} || true && docker container rm ${{ env.CONTAINER_NAME }} || true
            docker run -d -p 1080:1080 -e USERNAME=${{ secrets.TOR_CLIENT_USER }} -e PASSWORD=${{ secrets.TOR_CLIENT_PASSWORD }} \
            --restart always --name ${{ env.CONTAINER_NAME }} ${{ vars.IMAGE_NAME }}:${{ inputs.version }}
            
            echo "Waiting for container to become healthy..."
            for i in {1..10}; do
              STATUS=$(docker inspect --format '{{.State.Health.Status}}' ${{ env.CONTAINER_NAME }})
              echo "Container status: $STATUS"
              if [ "$STATUS" = "healthy" ]; then
                echo "Container is healthy!"
                exit 0
              fi
              sleep 10
            done
            
            echo "Container did not become healthy in time."
            docker logs ${{ env.CONTAINER_NAME }}
            exit 1