name: Test & Merge Dependabot PR

on: pull_request

concurrency:
  group: ${{github.ref_name}}
  cancel-in-progress: false

jobs:
  test:
    runs-on: ubuntu-latest
    name: Testing
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build the container image
        run: docker build -t test .

      - name: Run the container image
        run: docker run -d -p 9050:9050 test

      - name: Test the container image
        run: curl --socks5 localhost:9050 --socks5-hostname localhost:9050 https://check.torproject.org/api/ip | grep '"IsTor":true' || exit 1

  auto-merge:
    if: github.actor == 'dependabot[bot]'
    needs: test
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    name: Merge Dependabot PR
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
