name: Pipeline

on:
  push:
    branches:
      - 'master'
  pull_request:

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  build:
    uses: ./.github/workflows/build_test.yml
    secrets: inherit

  deploy:
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      version: ${{ needs.build.outputs.version }}
    needs: build

  auto-merge:
    if: github.actor == 'dependabot[bot]'
    needs: deploy
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    name: Merge Dependabot PR
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
