name: Pipeline

on:
  push:
    branches:
      - 'master'
  pull_request:

concurrency:
  group: single
  cancel-in-progress: false

env:
  GAR: europe-west4-docker.pkg.dev
  IMAGE_NAME: europe-west4-docker.pkg.dev/woladen-autos/docker/tor-client

jobs:
  pipeline:
    name: Build and run test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set short git commit SHA
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "SHORT_SHA=$calculatedSha" >> $GITHUB_ENV

      - name: Build the container image
        run: docker build -t ${{ env.IMAGE_NAME }} .

      - name: Run the container image
        run: docker run -d -p 32905:32905 ${{ env.IMAGE_NAME }}

      - name: Sleep for 30 seconds
        run: sleep 30s
        shell: bash

      - name: Test the container image
        run: curl --socks5 localhost:32905 --socks5-hostname localhost:32905 https://check.torproject.org/api/ip | grep '"IsTor":true' || exit 1

  auto-merge:
    if: github.actor == 'dependabot[bot]'
    needs: pipeline
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    name: Merge Dependabot PR
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
